In [2]:
import numpy as np
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [3]:
arr=np.linspace(0,1,6)
print(arr)

[0.  0.2 0.4 0.6 0.8 1. ]


In [5]:
arr=np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:

print("arr:",arr.flatten())

arr: [1 2 3 4 5 6 7 8 9]


In [9]:
arr=[[1,2,3],[6,7,8]]
print(arr)
print("sum:",np.sum(arr))
print("colsum:",np.sum(arr,axis=0))
print("rowsum:",np.sum(arr,axis=1))
print("avg:",np.mean(arr,axis=1))
print("max value:",np.max(arr))
print("min value",np.min(arr))
print("max value index:",np.argmax(arr))
print("std:",np.std(arr))

[[1, 2, 3], [6, 7, 8]]
sum: 27
colsum: [ 7  9 11]
rowsum: [ 6 21]
avg: [2. 7.]
max value: 8
min value 1
max value index: 5
std: 2.6299556396765835


In [13]:
a=[3,6,8,1,9,3]
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)
idx = np.where(a > 4)
print("Indices where value > 4:", idx)
print("Values > 4:", a[idx])

Sorted Array: [1 3 3 6 8 9]


TypeError: '>' not supported between instances of 'list' and 'int'