In [1]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

s1_1 = pd.Series([10, 20, 30, 40, 50])

np_array1_2 = np.random.randint(1, 101, size=(3, 4))

df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("s1_1:")
print(s1_1)
print("np_array1_2:")
print(np_array1_2)
print("df1_3:")
print(df1_3)


print("\n--- Task 2: Synthetic Data Generation for Practice ---")

df_sales = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', end='2023-04-09', periods=100),
    'Region': np.random.choice(['East', 'West', 'North', 'South'], 100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 100),
    'Sales': np.random.randint(100, 1001, 100),
    'Quantity': np.random.randint(1, 11, 100)
})

sales_nan_indices = np.random.choice(df_sales.index, 5, replace=False)
quantity_nan_indices = np.random.choice(df_sales.index, 3, replace=False)

df_sales.loc[sales_nan_indices, 'Sales'] = np.nan
df_sales.loc[quantity_nan_indices, 'Quantity'] = np.nan

print(df_sales)


print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

df3_1 = df_sales[['Region', 'Sales']]

df3_2 = df_sales[df_sales['Product'] == 'Laptop']

df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]

monitor_rows = df_sales[df_sales['Product'] == 'Monitor']
val3_4 = df_sales.loc[monitor_rows.index[0], 'Sales']
val3_4 = df_sales.iloc[monitor_rows.index[0], df_sales.columns.get_loc('Sales')]

print("df3_1:")
print(df3_1)
print("df3_2:")
print(df3_2)
print("df3_3:")
print(df3_3)
print("val3_4:", val3_4)


print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

missing_counts4_1 = df_sales.isnull().sum()

df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(
    df4_2_filled['Sales'].mean()
)

df4_3_dropped = df_sales.dropna()

print("missing_counts4_1:")
print(missing_counts4_1)
print("df4_2_filled:")
print(df4_2_filled)
print("df4_3_dropped:")
print(df4_3_dropped)


print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)

df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("df5_2_sorted:")
print(df5_2_sorted)
print("df5_3_grouped_region:")
print(df5_3_grouped_region)
print("df5_4_grouped_product:")
print(df5_4_grouped_product)

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64
np_array1_2:
[[61  7 39 37]
 [87 91 21 54]
 [13 47 21 71]]
df1_3:
    A   B   C   D
0  61   7  39  37
1  87  91  21  54
2  13  47  21  71

--- Task 2: Synthetic Data Generation for Practice ---
                            Date Region   Product  Sales  Quantity
0  2023-01-01 00:00:00.000000000  North  Keyboard  430.0       3.0
1  2023-01-01 23:45:27.272727272   East   Monitor  290.0       5.0
2  2023-01-02 23:30:54.545454545   East   Monitor  123.0       8.0
3  2023-01-03 23:16:21.818181818  South    Laptop  905.0       2.0
4  2023-01-04 23:01:49.090909090   West     Mouse  552.0       9.0
..                           ...    ...       ...    ...       ...
95 2023-04-05 00:58:10.909090910  North  Keyboard  455.0       1.0
96 2